version: '3.8'

services:
  db:
    image: postgres:15.0
    container_name: 'artofpostgressql-db'
    labels:
      application: 'artofpostgressql-db'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres_data:
